version = "3.10.7"
runner.dialect = scala3
maxColumn = 120

runner.scala3.rewrites = [
  SortImports
  UnlessWhen
  // Add other specific rewrites if needed
]

rewrite.scala3.convertToNewSyntax = yes
rewrite.scala3.removeOptionalBraces = yes
